export const PRODUCT_CATEGORIES = Object.freeze({
    ALL: "All",
    SURFACTANTS: "Surfactants",
    PERSONAL_CARE: "Personal Care",
    EMULSIFIERS: "Emulsifiers",
    INDUSTRIAL: "Industrial",
});

export const PRODUCT_CATEGORY_FILTERS = [
    PRODUCT_CATEGORIES.ALL,
    PRODUCT_CATEGORIES.SURFACTANTS,
    PRODUCT_CATEGORIES.PERSONAL_CARE,
    PRODUCT_CATEGORIES.EMULSIFIERS,
    PRODUCT_CATEGORIES.INDUSTRIAL,
];
